services:
  postgres-db:
    image: postgres:16-alpine
    container_name: production_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Tambahan: Cek denyut nadi database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  database-migration:
    image: migrate/migrate
    container_name: production_migration
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${DB_NAME}?sslmode=disable",
        "up",
      ]
    depends_on:
      postgres-db:
        condition: service_healthy # Tunggu sampai healthcheck bilang OK
    restart: on-failure

  app-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production_go_api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432 # Gunakan port internal Docker
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      postgres-db:
        condition: service_healthy
      database-migration:
        condition: service_completed_successfully # Tunggu migrasi BERHASIL baru app nyala

volumes:
  postgres_data:
