global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "go-wallet-api"
    static_configs:
      - targets: ["production_go_api:8080"]
